# .reltech.yml
version: 1

project:
  name: "Local First Auth Simulator"
  description: "Development tool for testing projects that use the package local-first-auth to add a simple onboarding flow to their app. This injects the window.localFirstAuth API into a regular browser, allowing you to test your app locally without having to create an account or use an app like Antler.
  builder: "Daniel Mathews"

tags:
  - dev-tools
  - local-first-auth
  - mini-apps
  - simulator
  - qr-code
  - decentralized-identity
  - onboarding

watch:
  branches: ["main"]
  signals: ["releases", "prs", "commits"]
  threshold: "minor"

preferences:
  summarize_commits: true
  summarize_readme: true
  public_link: true
  name_contributors: false

interests:
  - local-first-auth
  - client-side-auth
  - decentralized-identity
  - mini-apps
  - onboarding
